import DOMPurify, { type Config } from 'dompurify';

const PURIFY_CONFIG: Config = {
  ALLOWED_TAGS: [
    // Structure
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'p',
    'div',
    'span',
    'br',
    'hr',
    // Lists
    'ul',
    'ol',
    'li',
    // Tables
    'table',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'th',
    'td',
    'caption',
    'colgroup',
    'col',
    // Inline formatting
    'a',
    'strong',
    'b',
    'em',
    'i',
    'u',
    's',
    'del',
    'ins',
    'code',
    'pre',
    'kbd',
    'samp',
    'var',
    'blockquote',
    'cite',
    'q',
    // Media
    'img',
    'figure',
    'figcaption',
    'picture',
    'source',
    'video',
    'audio',
    // Semantic
    'article',
    'section',
    'aside',
    'main',
    'details',
    'summary',
    'abbr',
    'mark',
    'small',
    'sub',
    'sup',
    'time',
    // Definition lists
    'dl',
    'dt',
    'dd',
  ],
  ALLOWED_ATTR: [
    'href',
    'title',
    'name',
    'src',
    'alt',
    'width',
    'height',
    'colspan',
    'rowspan',
    'scope',
    'span',
    'srcset',
    'type',
    'media',
    'poster',
    'datetime',
    'cite',
    'class',
  ],
  ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto):|[^a-z]|[a-z+.-]+(?:[^a-z+.\-:]|$))/i,
  KEEP_CONTENT: true,
  RETURN_DOM: false,
  RETURN_DOM_FRAGMENT: false,
};

export const sanitize = (html: string): string => DOMPurify.sanitize(html, PURIFY_CONFIG) as string;
